module.exports={
    getAdminLogin:(req,res)=>{
        res.render('adminLogin');
    },
    getAdminDashboard:(req,res)=>{
        res.render('adminDashboard');
    },
    getAdminJobPosting:(req,res)=>{
        res.render('adminJobPosting');
    }
};